redux: py3 update; scipy API call;  use bytes instead of str
- temporarily converting image to RGB to avoid:
  OSError: cannot write mode F as JPEG

- scipy.misc.toimage is deprecated in favor of Image.fromarray

- using io.BytesIO to avoid extra encoding/decoding steps